<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="AllegroServiceTestImplService" targetNamespace="http://ws.sample.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.sample.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://ws.sample.org/" schemaLocation="allegroservicetestimpl_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="SoapFault">
    <wsdl:part name="SoapFault" element="tns:SoapFault">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="doQuerySysStatus">
    <wsdl:part name="parameters" element="tns:doQuerySysStatus">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="doQuerySysStatusResponse">
    <wsdl:part name="parameters" element="tns:doQuerySysStatusResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="AllegroServiceTestImpl">
    <wsdl:operation name="doQuerySysStatus">
      <wsdl:input name="doQuerySysStatus" message="tns:doQuerySysStatus">
    </wsdl:input>
      <wsdl:output name="doQuerySysStatusResponse" message="tns:doQuerySysStatusResponse">
    </wsdl:output>
      <wsdl:fault name="SoapFault" message="tns:SoapFault">
    </wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AllegroServiceTestImplServiceSoapBinding" type="tns:AllegroServiceTestImpl">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="doQuerySysStatus">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="doQuerySysStatus">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="doQuerySysStatusResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="SoapFault">
        <soap:fault name="SoapFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AllegroServiceTestImplService">
    <wsdl:port name="AllegroServiceTestImplPort" binding="tns:AllegroServiceTestImplServiceSoapBinding">
      <soap:address location="http://localhost:9090/AllegroServiceTestImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
