
package org.sample.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.15
 * Mon May 11 10:45:47 CEST 2015
 * Generated source version: 2.7.15
 */

@XmlRootElement(name = "doQuerySysStatus", namespace = "http://ws.sample.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "doQuerySysStatus", namespace = "http://ws.sample.org/")

public class DoQuerySysStatus {


}

