
package org.sample.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.15
 * Sun May 10 21:48:47 CEST 2015
 * Generated source version: 2.7.15
 */

@XmlRootElement(name = "getVersion", namespace = "http://ws.sample.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getVersion", namespace = "http://ws.sample.org/")

public class GetVersion {


}

