
package org.sample.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.15
 * Sun May 10 21:48:47 CEST 2015
 * Generated source version: 2.7.15
 */

@XmlRootElement(name = "getVersionResponse", namespace = "http://ws.sample.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getVersionResponse", namespace = "http://ws.sample.org/")

public class GetVersionResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

