
package org.sample.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.15
 * Mon May 11 10:45:48 CEST 2015
 * Generated source version: 2.7.15
 */

@XmlRootElement(name = "SoapFault", namespace = "http://ksoap2.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoapFault", namespace = "http://ksoap2.org/")

public class SoapFaultBean {

    private java.lang.String message;

    public java.lang.String getMessage() {
        return this.message;
    }

    public void setMessage(java.lang.String newMessage)  {
        this.message = newMessage;
    }

}

